name: tmnationsforever
title: TrackMania Nations Forever
version: '2.11.26'
summary:  The most popular online PC racing game.
description: |
 The most popular online PC racing game. It fuels 7 different racing
 environments; hundreds of thousands of tracks and millions of players to
 compete with. You can download the car you are dreaming of, paint it, drive it
 through insane tracks made of loopings, ramps and off roads. It is all about
 you, your driving skills and the track in front of you.
 .
 Just to make sure we understand each other: this is pure arcade driving
 madness.

 *Note: This Windows application runs on Linux using the Wine compatibility layer.*
grade: stable

confinement: strict
base: core18

architectures:
  - build-on: amd64

environment:
  WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree,mshtml="    # Prevent pop-ups about Wine Mono and Wine Gecko
  SNAP_SOMMELIER_STRICT: "1"                               # Make Sommelier exit when unset variable is used. (useful to find bugs in sommelier)

apps:
  tmnationsforever:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "C:/Program Files (x86)/TmNationsForever/TmForever.exe"
      INSTALL_URL: "http://files.trackmaniaforever.com/tmnationsforever_setup.exe"
      INSTALL_FLAGS: "/silent"
    plugs:
      - home
      - network
      - network-bind
      - opengl
      - audio-playback
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network
  # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  # The sommelier script helps you snap Windows applications using Wine. It 
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git

# These plugs are used to connect the snap to the wine runtime.
plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable
